In [77]:
import csv
import pandas as pd

# 1

In [79]:
with open('../data/example2.csv',newline ='') as f:
    data_reader = csv.DictReader(f)
    for i in data_reader:
        print(i['班次1'])

06:30
06:32
06:33
06:34
06:36
06:38
06:39
06:41
06:42
06:43
06:44
06:45
06:46
06:47
06:48
06:49
06:50
06:51
06:53
06:55
06:57
06:58
07:00
07:01
07:03
07:05
07:07
07:09
07:10
07:12
07:14
07:16
07:18
07:20
07:21
07:23
07:24
07:25
07:00
07:02
07:03
07:04
07:06
07:08
07:09
07:11
07:12
07:13
07:14
07:15
07:16
07:17
07:18
07:19
07:20
07:21
07:23
07:25
07:27
07:28
07:30
07:31
07:33
07:35
07:37
07:39
07:40
07:42
07:44
07:46
07:48
07:49
07:51
07:53
07:54
07:55

# 2

In [80]:
time_1 = []
with open('../data/example2.csv',newline ='') as f:
    data_reader = csv.DictReader(f)
    for i in data_reader:
        time_1.append(i['班次1'])
time_1

['06:30',
 '06:32',
 '06:33',
 '06:34',
 '06:36',
 '06:38',
 '06:39',
 '06:41',
 '06:42',
 '06:43',
 '06:44',
 '06:45',
 '06:46',
 '06:47',
 '06:48',
 '06:49',
 '06:50',
 '06:51',
 '06:53',
 '06:55',
 '06:57',
 '06:58',
 '07:00',
 '07:01',
 '07:03',
 '07:05',
 '07:07',
 '07:09',
 '07:10',
 '07:12',
 '07:14',
 '07:16',
 '07:18',
 '07:20',
 '07:21',
 '07:23',
 '07:24',
 '07:25',
 '07:00',
 '07:02',
 '07:03',
 '07:04',
 '07:06',
 '07:08',
 '07:09',
 '07:11',
 '07:12',
 '07:13',
 '07:14',
 '07:15',
 '07:16',
 '07:17',
 '07:18',
 '07:19',
 '07:20',
 '07:21',
 '07:23',
 '07:25',
 '07:27',
 '07:28',
 '07:30',
 '07:31',
 '07:33',
 '07:35',
 '07:37',
 '07:39',
 '07:40',
 '07:42',
 '07:44',
 '07:46',
 '07:48',
 '07:49',
 '07:51',
 '07:53',
 '07:54',
 '07:55']

# 3

In [81]:
with open('../data/example2.csv') as f:
    data = pd.read_csv(f)
    data = data[[f'班次{i}' for i in range(1,12)]]

data

,班次1,班次2,班次3,班次4,班次5,班次6,班次7,班次8,班次9,班次10,班次11
0,06:30,07:50,09:10,10:30,12:00,13:20,14:40,16:10,18:10,19:40,21:10
1,06:32,07:52,09:12,10:32,12:02,13:22,14:42,16:12,18:12,19:42,21:12
2,06:33,07:53,09:13,10:33,12:03,13:23,14:43,16:13,18:13,19:43,21:13
3,06:34,07:55,09:15,10:35,12:05,13:24,14:45,16:15,18:15,19:45,21:15
4,06:36,07:57,09:17,10:37,12:07,13:26,14:47,16:17,18:17,19:47,21:17
...,...,...,...,...,...,...,...,...,...,...,...
71,07:49,09:43,11:03,12:23,13:53,15:33,16:53,18:13,19:33,20:53,22:03
72,07:51,09:45,11:05,12:25,13:55,15:35,16:55,18:15,19:35,20:55,22:05
73,07:53,09:47,11:07,12:27,13:57,15:37,16:57,18:17,19:37,20:57,22:07
74,07:54,09:49,11:09,12:29,13:59,15:39,16:59,18:19,19:39,20:59,22:09
75,07:55,09:50,11:10,12:30,14:00,15:40,17:00,18:20,19:40,21:00,22:10